# Generated by Django 5.0.6 on 2024-07-08 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soccer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('match_title', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('stat_name', models.CharField(max_length=100)),
                ('stat_value', models.FloatField()),
                ('stat_type', models.CharField(max_length=100)),
                ('over_multiplier', models.FloatField(null=True)),
                ('under_multiplier', models.FloatField(null=True)),
                ('bet365_over_odds', models.IntegerField(null=True)),
                ('bet365_under_odds', models.IntegerField(null=True)),
                ('kambi_over_odds', models.IntegerField(null=True)),
                ('kambi_under_odds', models.IntegerField(null=True)),
            ],
        ),
    ]
