# Generated by Django 5.0.6 on 2024-07-09 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparasion', '0002_soccer_total_odds_over_soccer_total_odds_under'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverOdds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('match_title', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('stat_name', models.CharField(max_length=100)),
                ('stat_value', models.FloatField()),
                ('stat_type', models.CharField(max_length=100)),
                ('over_multiplier', models.FloatField(null=True)),
                ('bet365_over_odds', models.IntegerField(null=True)),
                ('kambi_over_odds', models.IntegerField(null=True)),
                ('total_odds_over', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnderOdds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('match_title', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('stat_name', models.CharField(max_length=100)),
                ('stat_value', models.FloatField()),
                ('stat_type', models.CharField(max_length=100)),
                ('under_multiplier', models.FloatField(null=True)),
                ('bet365_under_odds', models.IntegerField(null=True)),
                ('kambi_under_odds', models.IntegerField(null=True)),
                ('total_odds_under', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Soccer',
        ),
    ]
